//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auto.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automobiles
    {
        public int idAuto { get; set; }
        public Nullable<int> idBrand { get; set; }
        public Nullable<int> idModel { get; set; }
        public Nullable<int> idKPP { get; set; }
        public Nullable<int> yearModel { get; set; }
        public Nullable<decimal> price { get; set; }
    }
}
