//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auto.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public int idImage { get; set; }
        public string image { get; set; }
        public Nullable<int> idAuto { get; set; }
    
        public virtual Automobiles Automobiles { get; set; }
    }
}
