//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auto.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Models
    {
        public int idModel { get; set; }
        public string nameModel { get; set; }
        public string typeModel { get; set; }
        public string classModel { get; set; }
    }
}
